# version: "3.8"
   
# services:
#   db:
#     image: postgres
#     environment:
#       - POSTGRES_DB=postgres
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/code
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db



# settings.py
   
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'postgres',
#         'USER': 'postgres',
#         'PASSWORD': 'postgres',
#         'HOST': 'db',
#         'PORT': 5432,
#     }
# }



version: "3.8"
services:

  database:
    image: keinos/sqlite3 #nouchka/sqlite3 : latest
    #stdin_open: true
    #tty: true
    volumes:
      - ./db/:/asimplecrudproject/db/
    restart: always


  webapp:
    build: .
            #context: .
            #dockerfile: Dockerfile-nginx
    ports:
      - "8080:80"
    depends_on: 
      - database
    restart: always